import { CardType } from "./cards"

// cardId: CardType
export const CARDS = INDEX_WORKER.concat(INDEX_BUILDINGS).concat(INDEX_ARISTOCRATS).concat(INDEX_EXCHANGE);
export const INITIAL_WORKER = CARDS.keys().slice(0,INDEX_WORKER.length)
export const INITIAL_BUILDINGS = CARDS.keys().slice(INDEX_WORKER.length, INDEX_WORKER.length + INDEX_BUILDINGS.length)
export const INITIAL_ARISTOCRATS = CARDS.keys().slice(INDEX_WORKER.length + INDEX_BUILDINGS.length, INDEX_WORKER.length + INDEX_BUILDINGS.length + INDEX_ARISTOCRATS.length)
export const INITIAL_EXCHANGE = CARDS.keys().slice(INDEX_WORKER.length + INDEX_BUILDINGS.length + INDEX_ARISTOCRATS.length, INDEX_WORKER.length + INDEX_BUILDINGS.length + INDEX_ARISTOCRATS.length + INDEX_EXCHANGE.length)
export const INDEX_WORKER = [
    CardType.Lumberack,
    CardType.Lumberack,
    CardType.Lumberack,
    CardType.Lumberack,
    CardType.Lumberack,
    CardType.Lumberack,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.CzarAndCarpenter,
]

export const INDEX_BUILDINGS = [
    CardType.Market,
    CardType.Market,
    CardType.Market,
    CardType.Market,
    CardType.Market,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.Firehouse,
    CardType.Firehouse,
    CardType.Firehouse,
    CardType.Hospital,
    CardType.Hospital,
    CardType.Hospital,
    CardType.Library,
    CardType.Library,
    CardType.Library,
    CardType.Theater,
    CardType.Theater,
    CardType.Academy,
    CardType.PotemkinViallage,
    CardType.Pub,
    CardType.Pub,
    CardType.WareHouse,
    CardType.Observatory,
    CardType.Observatory,
]

export const INDEX_ARISTOCRATS = [
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Administrator,
    CardType.Administrator,
    CardType.Administrator,
    CardType.Administrator,
    CardType.Administrator,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.Secratary,
    CardType.Secratary,
    CardType.Secratary,
    CardType.Secratary,
    CardType.Controller,
    CardType.Controller,
    CardType.Controller,
    CardType.Judge,
    CardType.Judge,
    CardType.MistressOfCeremonies,
    CardType.MistressOfCeremonies,
]


export const INDEX_EXCHANGE = [
    CardType.CarpenterWorkshop,
    CardType.GoldSmelter,
    CardType.WeavingMill,
    CardType.WeavingMill,
    CardType.FurShop,
    CardType.FurShop,
    CardType.FurShop,
    CardType.Wharf,
    CardType.Wharf,
    CardType.Wharf,
    CardType.Bank,
    CardType.Peterhof,
    CardType.StIsaacsCathedral,
    CardType.MarinksyTheater,
    CardType.ChurchOfTheResurrection,
    CardType.Harbor,
    CardType.CathedralOfTheGreatPalace,
    CardType.SmolnyCathedral,
    CardType.Hermitage,
    CardType.WinterPalace,
    CardType.Abbot,
    CardType.WeaponMaster,
    CardType.ChamberMaid,
    CardType.Builder,
    CardType.Senator,
    CardType.Patriarch,
    CardType.Taxman,
    CardType.Admiral,
    CardType.MinisterOfForeignAffairs,
    CardType.Czarin,
]