
export const CardType = {
    Lumberjack: 0,
    Goldminer: 1,
    Sheperd: 2,
    FurTrapper: 3,
    ShipBuilder: 4,
    CzarAndCarpenter: 5,

    Market: 6,
    CustomsHouse: 7,
    Firehouse: 8,
    Hospital: 9,
    Library: 10,
    Theater: 11,
    Academy: 12,
    PotemkinViallage: 13,
    Pub: 14,
    WareHouse: 15,
    Observatory: 16,

    Author: 17,
    Administrator: 18,
    WarehouseManager: 19,
    Secratary: 20,
    Controller: 21,
    Judge: 22,
    MistressOfCeremonies: 23,

    CarpenterWorkshop: 24,
    GoldSmelter: 25,
    WeavingMill: 26,
    FurShop: 27,
    Wharf: 28,
    Bank: 29,
    Peterhof: 30,
    StIsaacsCathedral: 31,
    MarinksyTheater: 32,
    ChurchOfTheResurrection: 33,
    Harbor: 34,
    CathedralOfTheGreatPalace: 35,
    SmolnyCathedral: 36,
    Hermitage: 37,
    WinterPalace: 38,
    Abbot: 39,
    WeaponMaster: 40,
    ChamberMaid: 41,
    Builder: 42,
    Senator: 43,
    Patriarch: 44,
    Taxman: 45,
    Admiral: 46,
    MinisterOfForeignAffairs: 47,
    Czarin: 48,
}

export const INDEX_WORKER = [
    CardType.Lumberjack,
    CardType.Lumberjack,
    CardType.Lumberjack,
    CardType.Lumberjack,
    CardType.Lumberjack,
    CardType.Lumberjack,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Goldminer,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.Sheperd,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.FurTrapper,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.ShipBuilder,
    CardType.CzarAndCarpenter,
]

export const INDEX_BUILDINGS = [
    CardType.Market,
    CardType.Market,
    CardType.Market,
    CardType.Market,
    CardType.Market,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.CustomsHouse,
    CardType.Firehouse,
    CardType.Firehouse,
    CardType.Firehouse,
    CardType.Hospital,
    CardType.Hospital,
    CardType.Hospital,
    CardType.Library,
    CardType.Library,
    CardType.Library,
    CardType.Theater,
    CardType.Theater,
    CardType.Academy,
    CardType.PotemkinViallage,
    CardType.Pub,
    CardType.Pub,
    CardType.WareHouse,
    CardType.Observatory,
    CardType.Observatory,
]

export const INDEX_ARISTOCRATS = [
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Author,
    CardType.Administrator,
    CardType.Administrator,
    CardType.Administrator,
    CardType.Administrator,
    CardType.Administrator,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.WarehouseManager,
    CardType.Secratary,
    CardType.Secratary,
    CardType.Secratary,
    CardType.Secratary,
    CardType.Controller,
    CardType.Controller,
    CardType.Controller,
    CardType.Judge,
    CardType.Judge,
    CardType.MistressOfCeremonies,
    CardType.MistressOfCeremonies,
]


export const INDEX_EXCHANGE = [
    CardType.CarpenterWorkshop,
    CardType.GoldSmelter,
    CardType.WeavingMill,
    CardType.WeavingMill,
    CardType.FurShop,
    CardType.FurShop,
    CardType.FurShop,
    CardType.Wharf,
    CardType.Wharf,
    CardType.Wharf,
    CardType.Bank,
    CardType.Peterhof,
    CardType.StIsaacsCathedral,
    CardType.MarinksyTheater,
    CardType.ChurchOfTheResurrection,
    CardType.Harbor,
    CardType.CathedralOfTheGreatPalace,
    CardType.SmolnyCathedral,
    CardType.Hermitage,
    CardType.WinterPalace,
    CardType.Abbot,
    CardType.WeaponMaster,
    CardType.ChamberMaid,
    CardType.Builder,
    CardType.Senator,
    CardType.Patriarch,
    CardType.Taxman,
    CardType.Admiral,
    CardType.MinisterOfForeignAffairs,
    CardType.Czarin,
]

// cardId: CardType
export const CARDS = INDEX_WORKER.concat(INDEX_BUILDINGS).concat(INDEX_ARISTOCRATS).concat(INDEX_EXCHANGE);
export const INITIAL_WORKER = Array.from(CARDS.keys()).slice(0,INDEX_WORKER.length)
export const INITIAL_BUILDINGS = Array.from(CARDS.keys()).slice(INDEX_WORKER.length, INDEX_WORKER.length + INDEX_BUILDINGS.length)
export const INITIAL_ARISTOCRATS = Array.from(CARDS.keys()).slice(INDEX_WORKER.length + INDEX_BUILDINGS.length, INDEX_WORKER.length + INDEX_BUILDINGS.length + INDEX_ARISTOCRATS.length)
export const INITIAL_EXCHANGE = Array.from(CARDS.keys()).slice(INDEX_WORKER.length + INDEX_BUILDINGS.length + INDEX_ARISTOCRATS.length, INDEX_WORKER.length + INDEX_BUILDINGS.length + INDEX_ARISTOCRATS.length + INDEX_EXCHANGE.length)